#!/usr/bin/env python3
"""
Admin Credential Setup Script for College Voice Agent
This script helps you create secure admin credentials for the system.
"""

import os
import secrets
import string
from pathlib import Path

def generate_secure_password(length=16):
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return password

def generate_secret_key(length=64):
    """Generate a secure secret key for JWT."""
    return secrets.token_urlsafe(length)

def update_env_file(admin_username, admin_password, secret_key):
    """Update or create .env file with admin credentials."""
    env_file = Path(__file__).parent / ".env"
    
    # Read existing .env file if it exists
    existing_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key.strip()] = value.strip()
    
    # Update with new credentials
    existing_vars['ADMIN_USERNAME'] = admin_username
    existing_vars['ADMIN_PASSWORD'] = admin_password
    existing_vars['SECRET_KEY'] = secret_key
    
    # Write back to .env file
    with open(env_file, 'w') as f:
        f.write("# College Voice Agent Configuration\n")
        f.write("# Generated by setup_admin.py\n\n")
        
        # Write admin credentials first
        f.write("# Admin Authentication\n")
        f.write(f"ADMIN_USERNAME={existing_vars.get('ADMIN_USERNAME', 'admin')}\n")
        f.write(f"ADMIN_PASSWORD={existing_vars.get('ADMIN_PASSWORD', 'admin')}\n")
        f.write(f"SECRET_KEY={existing_vars.get('SECRET_KEY', 'supersecretkey')}\n\n")
        
        # Write other variables
        f.write("# API Keys\n")
        if 'GROQ_API_KEY' in existing_vars:
            f.write(f"GROQ_API_KEY={existing_vars['GROQ_API_KEY']}\n")
        if 'SPEECHMATICS_API_KEY' in existing_vars:
            f.write(f"SPEECHMATICS_API_KEY={existing_vars['SPEECHMATICS_API_KEY']}\n")
        
        f.write("\n# Directories\n")
        for key in ['CHROMA_PERSIST_DIR', 'UPLOAD_DIR', 'TEMP_AUDIO_DIR']:
            if key in existing_vars:
                f.write(f"{key}={existing_vars[key]}\n")
        
        f.write("\n# College Information\n")
        for key in ['COLLEGE_NAME', 'ADMISSIONS_PHONE', 'SUPPORT_EMAIL']:
            if key in existing_vars:
                f.write(f"{key}={existing_vars[key]}\n")
        
        # Write any remaining variables
        f.write("\n# Other Settings\n")
        written_keys = {'ADMIN_USERNAME', 'ADMIN_PASSWORD', 'SECRET_KEY', 
                       'GROQ_API_KEY', 'SPEECHMATICS_API_KEY',
                       'CHROMA_PERSIST_DIR', 'UPLOAD_DIR', 'TEMP_AUDIO_DIR',
                       'COLLEGE_NAME', 'ADMISSIONS_PHONE', 'SUPPORT_EMAIL'}
        for key, value in existing_vars.items():
            if key not in written_keys:
                f.write(f"{key}={value}\n")

def main():
    print("=" * 60)
    print("College Voice Agent - Admin Credential Setup")
    print("=" * 60)
    print()
    
    # Option 1: Use default credentials
    print("Choose an option:")
    print("1. Use default credentials (admin/admin) - NOT RECOMMENDED for production")
    print("2. Set custom username and password")
    print("3. Generate secure random password")
    print()
    
    choice = input("Enter your choice (1/2/3): ").strip()
    
    if choice == "1":
        admin_username = "admin"
        admin_password = "admin"
        print("\n⚠️  WARNING: Using default credentials is NOT secure!")
        print("   Username: admin")
        print("   Password: admin")
        
    elif choice == "2":
        admin_username = input("\nEnter admin username: ").strip()
        admin_password = input("Enter admin password: ").strip()
        confirm_password = input("Confirm admin password: ").strip()
        
        if admin_password != confirm_password:
            print("\n❌ Passwords don't match! Exiting.")
            return
        
        if len(admin_password) < 8:
            print("\n⚠️  WARNING: Password is too short! Recommended minimum: 8 characters")
            proceed = input("Continue anyway? (y/n): ").strip().lower()
            if proceed != 'y':
                return
    
    elif choice == "3":
        admin_username = input("\nEnter admin username (or press Enter for 'admin'): ").strip()
        if not admin_username:
            admin_username = "admin"
        
        admin_password = generate_secure_password(16)
        print(f"\n✅ Generated secure password: {admin_password}")
        print("   ⚠️  IMPORTANT: Save this password securely!")
    
    else:
        print("\n❌ Invalid choice! Exiting.")
        return
    
    # Generate secure secret key for JWT
    secret_key = generate_secret_key(64)
    
    # Update .env file
    print("\n📝 Updating .env file...")
    update_env_file(admin_username, admin_password, secret_key)
    
    print("\n" + "=" * 60)
    print("✅ Admin credentials configured successfully!")
    print("=" * 60)
    print(f"\nUsername: {admin_username}")
    print(f"Password: {admin_password}")
    print("\n⚠️  IMPORTANT:")
    print("   1. Save these credentials securely")
    print("   2. Restart the backend server for changes to take effect")
    print("   3. Use these credentials to login at /token endpoint")
    print("\n📖 How to login:")
    print("   POST http://localhost:8000/token")
    print("   Body (form-data):")
    print(f"     username: {admin_username}")
    print(f"     password: {admin_password}")
    print("\n🔄 To restart the server:")
    print("   1. Stop the current server (Ctrl+C)")
    print("   2. Run: python -m uvicorn app.main:app --reload")
    print("=" * 60)

if __name__ == "__main__":
    main()
